<?php
declare(strict_types=1);require_once __DIR__.'/config/config.php';$done=false;$error=null;
if ($_SERVER['REQUEST_METHOD']==='POST') {try {if (INITIAL_USER_PASSWORD === '' || str_starts_with(INITIAL_USER_PASSWORD, 'YOUR_')) {throw new RuntimeException('Configura INITIAL_USER_PASSWORD antes de ejecutar la instalación.');}$pdo=new PDO('mysql:host='.DB_HOST.';port='.DB_PORT.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$sql=file_get_contents(__DIR__.'/database/schema.sql');foreach (array_filter(array_map('trim',preg_split('/;\s*(?:\r?\n|$)/',$sql))) as $q) {if ($q!=='')$pdo->exec($q);}
$roles=['ADMINISTRADOR','SUPERVISOR','GERENTE','RECEPCIONISTA','REPRESENTANTE','DEALER','CONSULTA','MONITOR'];$st=$pdo->prepare('INSERT IGNORE INTO roles(nombre) VALUES(?)');foreach ($roles as $r)$st->execute([$r]);
$pdo->exec("INSERT IGNORE INTO localidades(nombre,codigo,cantidad_estaciones) VALUES('Tienda Principal','TP',6)");$loc=(int)$pdo->query("SELECT id FROM localidades ORDER BY id LIMIT 1")->fetchColumn();
$st=$pdo->prepare('INSERT IGNORE INTO estaciones(nombre,localidad_id) VALUES(?,?)');for ($i=1;$i<=6;$i++)$st->execute(['Estación '.str_pad((string)$i,2,'0',STR_PAD_LEFT),$loc]);$pdo->prepare('UPDATE localidades SET cantidad_estaciones=6 WHERE id=?')->execute([$loc]);
$services=[['Pagos','P','Gestiones de pago y facturación','bi-credit-card-fill','REPRESENTANTE',1],['Servicio al Cliente','S','Consultas y gestiones de servicio','bi-person-lines-fill','REPRESENTANTE',2],['Ventas','V','Ventas y contratación de servicios','bi-cart-fill','DEALER',3],['Soporte Técnico','T','Soporte y diagnóstico técnico','bi-tools','REPRESENTANTE',4],['Reclamos','R','Reclamos y casos especiales','bi-exclamation-diamond-fill','REPRESENTANTE',5],['Otros','O','Otras gestiones','bi-three-dots','REPRESENTANTE',6],['Activaciones','A','Nuevas activaciones de líneas y servicios','bi-phone-fill','DEALER',7],['Venta de Equipos','E','Venta de equipos y accesorios','bi-phone-vibrate-fill','DEALER',8]];$st=$pdo->prepare('INSERT IGNORE INTO servicios(nombre,prefijo,descripcion,icono,destino,orden) VALUES(?,?,?,?,?,?)');foreach ($services as $x)$st->execute($x);
$classes=['Pagos','Activaciones','Servicios','Reparaciones','Migración Masiva','Consulta general'];$st=$pdo->prepare('INSERT IGNORE INTO clasificaciones(nombre) VALUES(?)');foreach ($classes as $c)$st->execute([$c]);
$role=$pdo->prepare('SELECT id FROM roles WHERE nombre=?');$map=$pdo->prepare('INSERT IGNORE INTO rol_servicio(rol_id,servicio_id) VALUES(?,?)');$role->execute(['DEALER']);$dealer=(int)$role->fetchColumn();$role->execute(['REPRESENTANTE']);$rep=(int)$role->fetchColumn();$ds=$pdo->query("SELECT id FROM servicios WHERE nombre IN ('Activaciones','Ventas','Venta de Equipos')")->fetchAll(PDO::FETCH_COLUMN);$rs=$pdo->query("SELECT id FROM servicios WHERE nombre NOT IN ('Activaciones','Ventas','Venta de Equipos')")->fetchAll(PDO::FETCH_COLUMN);foreach ($ds as $id)$map->execute([$dealer,$id]);foreach ($rs as $id)$map->execute([$rep,$id]);
$station=(int)$pdo->query("SELECT id FROM estaciones WHERE localidad_id=$loc ORDER BY id LIMIT 1")->fetchColumn();$hash=password_hash(INITIAL_USER_PASSWORD,PASSWORD_DEFAULT);$ins=$pdo->prepare('INSERT IGNORE INTO usuarios(nombre,usuario,password_hash,rol_id,estacion_id,localidad_id) VALUES(?,?,?,?,?,?)');$defaults=[['Administrador','admin','ADMINISTRADOR',null,null],['Supervisor General','supervisor','SUPERVISOR',null,$loc],['Recepción Principal','recepcion','RECEPCIONISTA',null,$loc],['Representante Demo','representante','REPRESENTANTE',$station,$loc],['Dealer Demo','dealer','DEALER',$station,$loc],['Usuario Consulta','consulta','CONSULTA',null,null],['Monitor Tienda Principal','monitor','MONITOR',null,$loc]];foreach ($defaults as $u) {$role->execute([$u[2]]);$rid=(int)$role->fetchColumn();$ins->execute([$u[0],$u[1],$hash,$rid,$u[3],$u[4]]);}
$pdo->exec("CREATE TABLE IF NOT EXISTS gerente_localidades(gerente_id INT NOT NULL,localidad_id INT NOT NULL,PRIMARY KEY(gerente_id,localidad_id),FOREIGN KEY(gerente_id) REFERENCES usuarios(id) ON DELETE CASCADE,FOREIGN KEY(localidad_id) REFERENCES localidades(id) ON DELETE CASCADE)");$done=true;}catch (Throwable $e) {$error=$e->getMessage();}}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Instalación · VIVA TURNOS</title><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/app.css"></head><body class="login">
<div class="login-card"><div class="login-brand"><img class="login-logo" src="<?=BASE_URL?>/assets/img/viva-logo.png" alt="VIVA">
<h1 class="login-title">Instalación</h1><div class="login-sub">Sistema centralizado de turnos por localidad</div></div><?php if($done):?>
<div class="card" style="background:#effaf0"><strong>Conexión e instalación completadas.</strong>
<p>Se prepararon localidades, roles, estaciones, usuarios, servicios y reglas de cola.</p>
<a class="btn btn-primary" href="<?=BASE_URL?>/">Ir al inicio de sesión</a></div>
<p class="login-sub" style="margin-top:18px">Usuarios iniciales: <strong>admin, supervisor, recepcion, representante, dealer, consulta, monitor</strong>. La contraseña inicial fue tomada de INITIAL_USER_PASSWORD y no se almacena en el código.
</p><?php else:if($error):?><div class="login-error"><strong>No se pudo completar la instalación.</strong><br><?=htmlspecialchars($error)?></div>
<?php endif;?><p class="login-sub">Usa la base de datos configurada para este entorno.</p><form method="post">
<button class="btn btn-primary" style="width:100%">Probar conexión e instalar VIVA TURNOS</button></form><?php endif;?></div></body></html>
